GET http://localhost:3000/cardapio

###

POST http://localhost:3000/cardapio HTTP/1.1
content-type: application/json

{
    "nome": "Cardapio de sushi",
}

###
PUT http://localhost:3000/cardapio HTTP/1.1
content-type: application/json

{
    "nome": "Cardapio de sushi",
    "_id": "6327774437615fdb2569273b",
    "__v": 0
}

###
DELETE  http://localhost:3000/cardapio HTTP/1.1
content-type: application/json

{
    "_id": "6327774437615fdb2569273b"
}