GET http://localhost:3000/usuario

###

POST http://localhost:3000/usuario HTTP/1.1
content-type: application/json

{
    "nome": "Admin",
    "sobrenome": "Principal",
    "email": "admin@admin.com",
    "senha": "password"
}

###
PUT http://localhost:3000/usuario HTTP/1.1
content-type: application/json

{
    "_id": "6327754b37615fdb25692722",
    "nome": "Admin 2",
    "email": "admin@admin.com",
    "senha": "password",
    "__v": 0
}

###
DELETE  http://localhost:3000/usuario HTTP/1.1
content-type: application/json

{
    "_id": "63276e2d37615fdb25692717"
}